"use client";

import type { Campaign } from "@/types";
import type PptxGenJSType from "pptxgenjs";
import { formatCurrencyINR } from "@/lib/utils";

// ─────────────────────────────────────────────────────────────
// Export Center. Turns a campaign into shareable artifacts:
// Markdown, PowerPoint (pptxgenjs), print-to-PDF, and clipboard.
// pptxgenjs is imported dynamically so it never bloats the bundle
// or breaks SSR.
// ─────────────────────────────────────────────────────────────

export function campaignToMarkdown(c: Campaign): string {
  const p = c.plan;
  const lines: string[] = [];
  lines.push(`# ${p.title}\n`);
  lines.push(`> ${p.summary}\n`);
  lines.push(`**City:** ${c.city}  |  **Budget:** ${formatCurrencyINR(c.budget)}\n`);
  lines.push(`\n## Objectives\n`);
  p.objectives.forEach((o) => lines.push(`- ${o}`));
  lines.push(`\n## Audience Personas\n`);
  p.personas.forEach((persona) => {
    lines.push(`### ${persona.name} (${persona.age})`);
    lines.push(`- **Motivation:** ${persona.motivation}`);
    lines.push(`- **Channels:** ${persona.channels.join(", ")}`);
    lines.push(`- **Objection:** ${persona.objection}\n`);
  });
  lines.push(`## Channel Strategy\n`);
  p.channels.forEach((ch) => lines.push(`- **${ch.channel}:** ${ch.strategy}`));
  lines.push(`\n## Budget Split\n`);
  lines.push(`| Channel | Amount | % | Rationale |`);
  lines.push(`| --- | --- | --- | --- |`);
  p.budgetSplit.forEach((b) =>
    lines.push(
      `| ${b.channel} | ${formatCurrencyINR(b.amount)} | ${b.percent}% | ${b.rationale} |`,
    ),
  );
  lines.push(`\n## Timeline\n`);
  p.timeline.forEach((t) => lines.push(`- **${t.phase}** (${t.window}): ${t.focus}`));
  lines.push(`\n## KPIs\n`);
  p.kpis.forEach((k) => lines.push(`- **${k.metric}:** ${k.target} — ${k.why}`));
  lines.push(`\n## Risks\n`);
  p.risks.forEach((r) =>
    lines.push(`- **[${r.severity.toUpperCase()}] ${r.risk}** → ${r.mitigation}`),
  );
  lines.push(`\n## Next Steps\n`);
  p.nextSteps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
  lines.push(`\n---\n*Generated by GrowthPilot AI*`);
  return lines.join("\n");
}

export function download(filename: string, content: string, type = "text/plain") {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportMarkdown(c: Campaign) {
  download(`${slug(c.plan.title)}.md`, campaignToMarkdown(c), "text/markdown");
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

export function exportPdf() {
  // Uses the browser's native print → "Save as PDF". Print styles in
  // globals ensure the campaign renders cleanly.
  window.print();
}

export async function exportPptx(c: Campaign) {
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  const p = c.plan;
  const PURPLE = "7C3AED";
  const DARK = "0F0F14";

  // Title slide
  let s = pptx.addSlide();
  s.background = { color: DARK };
  s.addText("GrowthPilot AI", { x: 0.5, y: 0.5, fontSize: 14, color: PURPLE, bold: true });
  s.addText(p.title, { x: 0.5, y: 1.6, w: 12, fontSize: 40, color: "FFFFFF", bold: true });
  s.addText(p.summary, { x: 0.5, y: 3.4, w: 12, fontSize: 16, color: "C4C4CC" });
  s.addText(`${c.city}  ·  ${formatCurrencyINR(c.budget)}`, {
    x: 0.5, y: 6.5, fontSize: 14, color: PURPLE, bold: true,
  });

  // Objectives + KPIs
  s = pptx.addSlide();
  s.background = { color: DARK };
  s.addText("Objectives & KPIs", { x: 0.5, y: 0.4, fontSize: 24, color: PURPLE, bold: true });
  s.addText(p.objectives.map((o) => `• ${o}`).join("\n"), {
    x: 0.5, y: 1.4, w: 6, fontSize: 14, color: "FFFFFF", lineSpacingMultiple: 1.4,
  });
  s.addText(p.kpis.map((k) => `• ${k.metric}: ${k.target}`).join("\n"), {
    x: 6.8, y: 1.4, w: 6, fontSize: 14, color: "FFFFFF", lineSpacingMultiple: 1.4,
  });

  // Budget split table
  s = pptx.addSlide();
  s.background = { color: DARK };
  s.addText("Budget Split", { x: 0.5, y: 0.4, fontSize: 24, color: PURPLE, bold: true });
  const rows: PptxGenJSType.TableRow[] = [
    ["Channel", "Amount", "%"].map((t) => ({
      text: t,
      options: { bold: true, color: "FFFFFF", fill: { color: PURPLE } },
    })),
    ...p.budgetSplit.map((b) => [
      { text: b.channel, options: { color: "FFFFFF" } },
      { text: formatCurrencyINR(b.amount), options: { color: "FFFFFF" } },
      { text: `${b.percent}%`, options: { color: "FFFFFF" } },
    ]),
  ];
  s.addTable(rows, { x: 0.5, y: 1.4, w: 9, border: { type: "solid", color: "333340" }, fill: { color: "1A1A22" } });

  // Timeline
  s = pptx.addSlide();
  s.background = { color: DARK };
  s.addText("Timeline", { x: 0.5, y: 0.4, fontSize: 24, color: PURPLE, bold: true });
  s.addText(
    p.timeline.map((t) => `${t.window} — ${t.phase}: ${t.focus}`).join("\n"),
    { x: 0.5, y: 1.4, w: 12, fontSize: 14, color: "FFFFFF", lineSpacingMultiple: 1.5 },
  );

  await pptx.writeFile({ fileName: `${slug(p.title)}.pptx` });
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "campaign";
}
